spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
jwt.secret=test-secret-key-for-testing-purposes-only
system.name=Pertindetu Test
system.version=0.0.1
base.api.domain=http://localhost:8080
spring.jpa.open-in-view=false
spring.autoconfigure.exclude=org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration